backend:
  name: github
  branch: master
  repo: Maneal689/blog
  open_authoring: true

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow


collections:
  - name: "post"
    label: "Post"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Hero", name: "hero", widget: "image" }
      - { label: "Description", name: "desc", widget: "string"  }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Article", name: "body", widget: "markdown" }
